### ISSUE TITLE
ExplorerBlurMica and Rectify11

### ISSUE THREAD

**Issue by WinExperiments** [Maplespe/ExplorerBlurMica#124]
In the latest Rectify11 Mica theme, ExplorerBlurMica doesn't affect the navigation pane.
![Screenshot 2024-03-13 212015](https://github.com/Maplespe/ExplorerBlurMica/assets/91428431/10f555b6-dcbb-4b4e-b27b-a7d7fbc0074b)
This is because the Rectify11 theme now makes the SysTreeView32 control composited, while the default theme does not.
![Screenshot 2024-03-13 212107](https://github.com/Maplespe/ExplorerBlurMica/assets/91428431/773af4cb-c456-454d-86aa-0157b1b7dde5)
![Screenshot 2024-03-13 212149](https://github.com/Maplespe/ExplorerBlurMica/assets/91428431/b85b14a9-7673-440a-9687-9e9184b3dfee)

**Comment by Maplespe** [comment]
Similar to #120, we are not responsible for third party themes. Because it brings a huge amount of work and a constant stream of trouble.
So you need to modify the theme yourself, thanks.

**Comment by ooTruffle** [comment]
Your readme says
> It is also compatible with third-party themes.

If your saying its a issue on the theme side then your not compatible with third party themes

**Comment by Maplespe** [comment]
> Your readme says
> 
> > It is also compatible with third-party themes.
> 
> If your saying its a issue on the theme side then your not compatible with third party themes

We can only guarantee basic compatibility, which means that most of the features work as expected and do not cause crashes.
The vast majority of third-party themes work just as well as the default theme because they all follow the properties of the default theme.
For such themes that use special properties, if everyone did so, our workload would be endless, which is obviously impossible and not in our area of responsibility.

And, to address the above, Rectify11's theme it was working fine before, but because of the changes it made later it caused incompatibility.

Finally, EBM was created before Rectify11. We can't predict the future, including what else it will change later, we can only follow the common standard for compatibility.
