### ISSUE TITLE
Feature Request: Only allow Titlebars and Border Blur/Transparency

### ISSUE THREAD

**Issue by TheDolphinSlayer** [Maplespe/ExplorerBlurMica#18]
Best program out there for AeroGlass blur for windows! Any chance we can get transparency like Windows 7? borders only with possible reflections?
![image](https://user-images.githubusercontent.com/73983610/229272465-a16d68fc-0264-4ef9-af26-d110e5a39afa.png)

**Comment by Maplespe** [comment]
I think StartAllBack does something similar, it extends the Mica effect from the title bar to the navigation bar Same as win7.
Also since Microsoft removed window borders from Windows 10 the Blur effect can't be extended to the borders unless the messtyles theme file is modified.
I will try to implement the "Only allow Titlebars and Border Blur" feature. But it is not possible to do the same as in Win7, and it will not work for windows other than explorer, this project is only for explorer.
Thank you.

**Comment by Maplespe** [comment]
We have implemented this feature in the new project, check out [DWMBlurGlass](https://github.com/Maplespe/DWMBlurGlass)
