### ISSUE TITLE
windows desktop watermark bug on 1.0.4+

### ISSUE THREAD

**Issue by MuscularPuky** [Maplespe/ExplorerBlurMica#21]
occurs when the explorer launches. 1.0.3 is fine
![스크린샷(635)](https://user-images.githubusercontent.com/93962018/236261192-699b080a-d059-4f3d-ab5e-eb13778ba334.png)

**Comment by Maplespe** [comment]
Well, I haven't tested the preview system.
I probably don't plan to fix this issue in the short term, as long as it doesn't affect the official version of the system.
The work may not be worth it because of the rapid iterations of the preview system.
I think you should be able to disable the watermark.
Thank you :)

**Comment by MuscularPuky** [comment]
I think that's not cuz of insider preview. although I don't have any stable version of Windows 10/11 but that insider preview watermark has same mechanism with–HKEY_CURRENT_USER\CONTROL PANEL\DESKTOP\PaintDesktopVersion in regedit so may can be test it ithink. ofc general users don't need to enable that key lol you right anyways I'll stuck to 1.0.3 be well :)
