### ISSUE TITLE
2.0v conflicts with TranslucentFlyouts

### ISSUE THREAD

**Issue by Undisputed00x** [Maplespe/ExplorerBlurMica#89]
Tweaked numerous settings and still when EBM 2.0v is enabled it disables some of the features of [TranslucentFlyouts](https://github.com/ALTaleX531/TranslucentFlyouts) like backdrop effect

**Comment by Maplespe** [comment]
Since TranslucentFlyouts checks if the target function has been taken over then it is not processed anymore, and EBM v2 has switched to an enhanced IATHook (previously it used inlinehook which could crash with infinite recursion due to TF).
But either way, either TF is invalid or EBM crashes unless the TF code is changed.
@ALTaleX531

**Comment by Undisputed00x** [comment]
So there is from now on there wont be any compatibility between too software unless someone makes some code changes for that to happen ?

**Comment by bbmaster123** [comment]
just want to say that turning off immersive menu's fixes the backdrop, which IMO is a decent work around for now. No stability issues so far.

**Comment by Maplespe** [comment]
[TranslucentFlyouts v3](https://github.com/ALTaleX531/TranslucentFlyouts/releases/tag/v3.0.0-insider-preview) version should now be compatible with this program.
